### ISSUE TITLE
Handle composite elements

### ISSUE THREAD

**Issue by mikeplate** [mikeplate/jquery-drag-drop-plugin#1]
The plugin assumes that every draggable element is a single element with no children. This should not be the case. It should have a way to recognize that a touched element might be part of a container and that the container should be dragged instead of the touched element.

**Comment by LeoDT** [comment]
line 76: var $element = $(event.target); => var $element = $(this);
maybe help.it's note tested.

**Comment by mikeplate** [comment]
Thanks for the tip @LeoDT. I used that and added support for overridable function canDrag to supplement it. Now composite elements work, as demonstrated by the "simple.html" example.
